const C=window.F1RSTME_CONFIG||{};let D=JSON.parse(localStorage.f1_devices||"null")||[
{name:"Galaxy S26 Ultra",brand:"Samsung",price:139999,specs:{display:"6.9-inch AMOLED",chip:"Snapdragon flagship",camera:"200MP",battery:"5000mAh",charging:"65W",storage:"256GB"}},
{name:"iPhone 18 Pro",brand:"Apple",price:129900,specs:{display:"6.3-inch OLED",chip:"A20 Pro",camera:"48MP",battery:"All-day",charging:"Fast",storage:"256GB"}},
{name:"Xiaomi 18 Pro",brand:"Xiaomi",price:79999,specs:{display:"6.7-inch AMOLED",chip:"Snapdragon flagship",camera:"50MP",battery:"6000mAh",charging:"90W",storage:"256GB"}},
{name:"Pixel 11 Pro",brand:"Google",price:109999,specs:{display:"6.3-inch OLED",chip:"Tensor",camera:"50MP",battery:"5000mAh",charging:"Fast",storage:"256GB"}}];
let R=JSON.parse(localStorage.f1_reviews||"null")||[{title:"Galaxy S26 Ultra Review",model:"Galaxy S26 Ultra",rating:9.2,text:"Premium flagship with strong display, cameras and AI features."},{title:"iPhone 18 Pro First Look",model:"iPhone 18 Pro",rating:9,text:"Performance-focused Pro phone with a polished ecosystem."},{title:"Xiaomi 18 Pro Review",model:"Xiaomi 18 Pro",rating:8.7,text:"Large battery, fast charging and an aggressive flagship feature set."}];
let S=JSON.parse(localStorage.f1_social||'{"youtube":"https://youtube.com/","instagram":"https://instagram.com/"}');
const E=x=>(x??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function phones(){phoneGrid.innerHTML=D.map(x=>`<article class="phone"><div class="pic">F1</div><small>${E(x.brand)}</small><h3>${E(x.name)}</h3><p>₹${Number(x.price).toLocaleString("en-IN")}</p></article>`).join("");a.innerHTML=b.innerHTML=D.map((x,i)=>`<option value="${i}">${E(x.name)}</option>`).join("");b.selectedIndex=1}
function reviews(){reviewGrid.innerHTML=R.map(x=>`<article class="review"><small>F1RSTME REVIEW</small><h3>${E(x.title)}</h3><b>${E(x.rating)}/10</b><p>${E(x.text)}</p></article>`).join("")}
function compare(){let x=D[a.value],y=D[b.value],K=["display","chip","camera","battery","charging","storage"];result.innerHTML='<div class="compare-table"><div>SPEC</div><div>'+E(x.name)+'</div><div>'+E(y.name)+'</div>'+K.map(k=>`<div>${k}</div><div>${E(x.specs?.[k]||"—")}</div><div>${E(y.specs?.[k]||"—")}</div>`).join("")+`<div>PRICE</div><div>₹${Number(x.price).toLocaleString("en-IN")}</div><div>₹${Number(y.price).toLocaleString("en-IN")}</div></div>`}
function news(){let n=[["Techtember brings a wave of new smartphone launches","Latest launch activity from major brands makes September a busy month for phone buyers."],["New AI PCs push more processing onto devices","On-device AI is becoming a major focus across the next generation of PCs."],["What to check before buying a smartphone","Compare chipset, display, camera, battery, software support and India pricing."]];newsGrid.innerHTML=n.map(x=>`<article class="news"><div class="pic">F1</div><h3>${E(x[0])}</h3><p>${E(x[1])}</p><a href="#phones">READ MORE ↗</a></article>`).join("")}
phones();reviews();news();compareBtn.onclick=compare;yt.href=S.youtube;ig.href=S.instagram;menuOpen.onclick=()=>menu.classList.add("open");menuClose.onclick=()=>menu.classList.remove("open");document.querySelectorAll(".panel a").forEach(x=>x.onclick=()=>menu.classList.remove("open"));